CONF_DIR="/data/adb/v2fly/"
PID_FILE="${CONF_DIR}/v2ray.pid"
LOG_FILE="${CONF_DIR}/v2ray.log"
LOG_TZ="${CONF_DIR}/zoneinfo/Asia/Shanghai"
APPID_FILE="${CONF_DIR}/appid.list"
CONF_FILE="${CONF_DIR}/client.json"
JSON_VER="v4"

V2FLY_BIN="${CONF_DIR}/bin/v2ray"

appid_file="${CONF_DIR}/appid.list"

dokodemo_port=12345

table_id=3338
mark=255
mark_v2fly=155

ipv4_fakedns="192.168.0.0/15"
ipv6_fakedns="fc00::/18"

rule_autorun="true"
