CONF_DIR="/data/adb/v2fly/"
PID_FILE="${CONF_DIR}/v2ray.pid"
LOG_FILE="${CONF_DIR}/v2ray.log"
APPID_FILE="${CONF_DIR}/appid.list"
CONF_FILE="${CONF_DIR}/client.json"
JSON_VER="v4"

DAEMON="${MOD_DIR}/v2ray/bin/v2ray"

appid_file="${CONF_DIR}/appid.list"

dokodemo_port=12345

table_id=12321
mark=255
mark_v2fly=155

ipv4_fakedns="192.168.0.0/15"
ipv6_fakedns="fc00::/18"
